update pre-commit

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,30 +1,32 @@
 git rm -r --cached build/ >/dev/null 2>&1 || true
-(while sleep 1; do printf '.'; done) &
-spinner_pid=$!
 
 echo "Scanning commit... 30-60s 💅🥱⏳"
 
-# Exit on any error
-set -e
-
-# Ensure cleanup happens even if script fails
-cleanup() {
-    echo "Detected secrets in staged files!"
-    kill $spinner_pid
-}
-
 if ! gitleaks protect --staged -v --redact; then
-    cleanup
+    echo "Gitleaks detected secrets in staged files"
     exit 1
 fi
 
-if ! git diff --staged --name-only -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline; then
-    cleanup
+git add .secrets.baseline
+if (git diff --staged --name-only -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline) | grep -q "Secret Type"; then
+    echo "$(git diff --staged --name-only -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline)"
+    echo "Detect-secrets detected secrets in staged files"
     exit 1
 fi
 
-kill $spinner_pid
+echo "No secrets detected in staged files! 🎉"
+
+if ! git diff --quiet; then
+    echo "Error: You have unstaged changes."
+    echo "The formatter in this pre-commit hook requires all changes to be staged."
+    echo "Tip: Use 'git stash --keep-index' to temporarily store your unstaged changes,"
+    echo "     then commit your staged changes, and finally 'git stash pop'"
+    exit 1
+fi
 
 npm install
 npm run format
+npm run format:backend
 npm run i18n:parse
+
+git add .
