Accessibility fixes for modals, part 1 (#355)
* cleanup some `alt` texts, fix model logo stretching tall issue in Safari

* add accessible name to close button for modals

* formatting

* change div to h2 for modal headings/title

* add proper labels and fix contrast in AddUserModal form

* fix contrast for user csv instructions on AddUserModal

* AddGroupModal -add form labels and contrast, add borders to input, semantic HTML

* cleanup, give consistent outline and border for AddUserModal

* rebase cleanup

* demonstrate passing a heading id for modal aria label

* more rebase cleanup

* Update modals for focus/heading fixes

* code cleanup

* remove old backend files

* hoist modal close button into top-level modal component

removes custom implementations of modal close button from each sub modal component

* Fix: npm run format

---------

Co-authored-by: Eleni Chappen <eleni.chappen@gsa.gov>

diff --git a/.husky/pre-commit b/.husky/pre-commit
--- a/.husky/pre-commit
+++ b/.husky/pre-commit
@@ -1,22 +1,30 @@
 git rm -r --cached build/ >/dev/null 2>&1 || true
+(while sleep 1; do printf '.'; done) &
+spinner_pid=$!
 
 echo "Scanning commit... 30-60s 💅🥱⏳"
 
+# Exit on any error
+set -e
+
+# Ensure cleanup happens even if script fails
+cleanup() {
+    echo "Detected secrets in staged files!"
+    kill $spinner_pid
+}
+
 if ! gitleaks protect --staged -v --redact; then
-    echo "Gitleaks detected secrets in staged files"
+    cleanup
     exit 1
 fi
 
-git add .secrets.baseline
-if (git diff --staged --name-only -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline) | grep -q "Secret Type"; then
-    echo "$(git diff --staged --name-only -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline)"
-    echo "Detect-secrets detected secrets in staged files"
+if ! git diff --staged --name-only -z | xargs -0 detect-secrets-hook --baseline .secrets.baseline; then
+    cleanup
     exit 1
 fi
 
-echo "No secrets detected in staged files! 🎉"
+kill $spinner_pid
 
 npm install
 npm run format
-npm run format:backend
 npm run i18n:parse
